
# ==============================================================================
# Configuration file: config.yml
# Author: Rodolfo Souza
# Date: 2025-10-04
# Description: Configures variables for installing Podman and Portainer.
# Notes:
#   - Commented out lines are optional settings, uncomment and modify as needed.
#   - install_portainer controls whether the Portainer playbook/role will run
#   - container_engine defines which container engine will be installed
#   - portainer_image, portainer_ports, portainer_volumes, and restart_policy
#     are used to configure the Portainer container
# License: MIT
# For more details, see the documentation.
# ==============================================================================

# --- Container Settings --- #
container_engine: podman 
install_portainer: true
# portainer_image: "portainer/portainer-ce:lts"
# portainer_edge_agent_port: 8000
# portainer_webui_port: 9443
# portainer_data_volume:
#   - "portainer_data:/data"
# portainer_podman_volume:
#   - "/run/podman/podman.sock:/var/run/docker.sock"
# portainer_docker_volume:
#   - "/var/run/docker.sock:/var/run/docker.sock"
# restart_policy: always
