- name: Rust Installation
  hosts: all
  become: true
  tasks:
    - name: Check if cargo is installed
      ansible.builtin.stat:
        path: /home/{{ ansible_user_id }}/.cargo/bin/cargo
      register: packaging_packages_cargo_exists

    - name: Download rustup installer script
      ansible.builtin.get_url:
        url: https://sh.rustup.rs
        dest: /tmp/rustup-init.sh
        mode: '0755'
      when: not packages_cargo_exists.stat.exists

    - name: Install Rust using rustup
      ansible.builtin.shell: |
        sh /tmp/rustup-init.sh -y
      args:
        creates: /home/{{ ansible_user_id }}/.cargo/bin/rustc
      become: false
      when: not packages_cargo_exists.stat.exists
